In [31]:
import requests
import pandas as pd

In [25]:
import requests

url = "https://open.er-api.com/v6/latest/GBP"
response = requests.get(url)

print(response.status_code)

200

In [26]:
data = response.json()
data

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1770508951,
 'time_last_update_utc': 'Sun, 08 Feb 2026 00:02:31 +0000',
 'time_next_update_unix': 1770597101,
 'time_next_update_utc': 'Mon, 09 Feb 2026 00:31:41 +0000',
 'time_eol_unix': 0,
 'base_code': 'GBP',
 'rates': {'GBP': 1,
  'AED': 4.992383,
  'AFN': 88.796055,
  'ALL': 111.421842,
  'AMD': 513.516414,
  'ANG': 2.43332,
  'AOA': 1282.171658,
  'ARS': 1974.183489,
  'AUD': 1.944202,
  'AWG': 2.43332,
  'AZN': 2.309187,
  'BAM': 2.251273,
  'BBD': 2.718793,
  'BDT': 166.341594,
  'BGN': 2.206834,
  'BHD': 0.511133,
  'BIF': 4043.262136,
  'BMD': 1.359396,
  'BND': 1.729249,
  'BOB': 9.414836,
  'BRL': 7.136489,
  'BSD': 1.359396,
  'BTN': 123.043596,
  'BWP': 19.10053,
  'BYN': 3.879519,
  'BZD': 2.718793,
  'CAD': 1.857522,
  'CDF': 3107.880597,
  'CHF': 1.055644,
  'CLF': 0.029712,
  'CLP': 1174.41823,
  'CNH': 9.42671,
  'CNY': 9.451003,
  'COP': 4947.660873,
  'CRC': 674.302815,
  'CUP': 32.625515,
  'CVE': 126.92134,
  'CZK': 27.915468,
  'DJF': 241.593296,
  'DKK': 8.58881,
  'DOP': 85.733221,
  'DZD': 176.702661,
  'EGP': 63.701932,
  'ERN': 20.390947,
  'ETB': 209.64207,
  'EUR': 1.15106,
  'FJD': 2.998235,
  'FKP': 1,
  'FOK': 8.588808,
  'GEL': 3.651488,
  'GGP': 1,
  'GHS': 14.972364,
  'GIP': 1,
  'GMD': 100.766938,
  'GNF': 11918.539347,
  'GTQ': 10.427058,
  'GYD': 285.048597,
  'HKD': 10.621369,
  'HNL': 35.918515,
  'HRK': 8.672642,
  'HTG': 178.353747,
  'HUF': 435.79604,
  'IDR': 22927.681761,
  'ILS': 4.247203,
  'IMP': 1,
  'INR': 123.044521,
  'IQD': 1787.364807,
  'IRR': 1599824.561404,
  'ISK': 167.011035,
  'JEP': 1,
  'JMD': 211.791861,
  'JOD': 0.963812,
  'JPY': 213.483936,
  'KES': 175.227078,
  'KGS': 118.820431,
  'KHR': 5479.684211,
  'KID': 1.944195,
  'KMF': 566.2831,
  'KRW': 1992.072867,
  'KWD': 0.415885,
  'KYD': 1.13283,
  'KZT': 673.8093,
  'LAK': 29461.521304,
  'LBP': 121665.981915,
  'LKR': 419.959882,
  'LRD': 252.725729,
  'LSL': 21.864158,
  'LYD': 8.609443,
  'MAD': 12.484157,
  'MDL': 23.096962,
  'MGA': 6026.398713,
  'MKD': 71.0103,
  'MMK': 2860.669931,
  'MNT': 4857.797914,
  'MOP': 10.939988,
  'MRU': 53.882262,
  'MUR': 62.491677,
  'MVR': 21.017617,
  'MWK': 2375.257953,
  'MXN': 23.533371,
  'MYR': 5.36098,
  'MZN': 86.793681,
  'NAD': 21.864158,
  'NGN': 1842.532333,
  'NIO': 50.037057,
  'NOK': 13.186526,
  'NPR': 196.869754,
  'NZD': 2.263793,
  'OMR': 0.522684,
  'PAB': 1.359396,
  'PEN': 4.571714,
  'PGK': 5.880372,
  'PHP': 79.607525,
  'PKR': 380.936158,
  'PLN': 4.856285,
  'PYG': 9015.366232,
  'QAR': 4.948203,
  'RON': 5.860702,
  'RSD': 135.243504,
  'RUB': 104.41348,
  'RWF': 1986.39934,
  'SAR': 5.097737,
  'SBD': 10.77967,
  'SCR': 18.795272,
  'SDG': 608.853801,
  'SEK': 12.284925,
  'SGD': 1.729251,
  'SHP': 1,
  'SLE': 33.278863,
  'SLL': 33278.758388,
  'SOS': 776.970149,
  'SRD': 52.057,
  'SSP': 6415.822816,
  'STN': 28.200905,
  'SYP': 154.131789,
  'SZL': 21.864158,
  'THB': 42.930078,
  'TJS': 12.654732,
  'TMT': 4.759177,
  'TND': 3.893961,
  'TOP': 3.200482,
  'TRY': 59.35823,
  'TTD': 9.473419,
  'TVD': 1.944195,
  'TWD': 42.998068,
  'TZS': 3496.516511,
  'UAH': 58.564517,
  'UGX': 4796.493105,
  'USD': 1.359401,
  'UYU': 52.438244,
  'UZS': 16684.008817,
  'VES': 520.149936,
  'VND': 35204.799787,
  'VUV': 161.430564,
  'WST': 3.651019,
  'XAF': 755.044133,
  'XCD': 3.67037,
  'XCG': 2.43332,
  'XDR': 0.989622,
  'XOF': 755.044133,
  'XPF': 137.357977,
  'YER': 324.034219,
  'ZAR': 21.85743,
  'ZMW': 25.723579,
  'ZWG': 34.7128,
  'ZWL': 34.7128}}

In [27]:
gbp_to_inr = data["rates"]["INR"]
gbp_to_inr

123.044521

In [1]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.11-cp39-cp39-win_amd64.whl (2.7 MB)
   ---------------------------------------- 2.7/2.7 MB 19.6 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

WARNING: Ignoring invalid distribution -atplotlib (c:\users\prana\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\prana\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\prana\anaconda3\lib\site-packages)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import psycopg2
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\prana\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\prana\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\prana\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
  File "C:\Users\prana\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\prana\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\prana\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\prana\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 367, in dispatch_shell
    await result
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 662, in execute_request
    reply_content = await reply_content
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2863, in run_cell
    result = self._run_cell(
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in _run_cell
    return runner(coro)
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3106, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3309, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\prana\AppData\Local\Temp\ipykernel_22148\2620677481.py", line 2, in <cell line: 2>
    import pandas as pd
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\__init__.py", line 80, in <module>
    from pandas.core.api import (
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\prana\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\prana\anaconda3\lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\prana\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\prana\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\prana\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
    self.io_loop.start()
  File "C:\Users\prana\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\prana\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\prana\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\prana\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 367, in dispatch_shell
    await result
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 662, in execute_request
    reply_content = await reply_content
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\prana\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2863, in run_cell
    result = self._run_cell(
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in _run_cell
    return runner(coro)
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3106, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3309, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\prana\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\prana\AppData\Local\Temp\ipykernel_22148\2620677481.py", line 2, in <cell line: 2>
    import pandas as pd
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\__init__.py", line 80, in <module>
    from pandas.core.api import (
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\prana\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\prana\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\prana\anaconda3\lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [15]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="postgres",   # default DB
    user="postgres",
    password="143Amresh@"
)

In [16]:
conn.autocommit = True

In [17]:
cursor = conn.cursor()

In [28]:
#cursor.execute("CREATE DATABASE pricing;")

In [19]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS staging_exchange_rates (
    rate_date DATE PRIMARY KEY,
    gbp_to_inr NUMERIC
);
""")

In [20]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS products (
    product_id TEXT PRIMARY KEY,
    title TEXT,
    price_gbp NUMERIC,
    price_inr NUMERIC,
    in_stock BOOLEAN,
    price_tier TEXT
);
""")

In [21]:
conn.commit()

In [29]:
cursor.execute("""
INSERT INTO staging_exchange_rates (rate_date, gbp_to_inr)
VALUES (CURRENT_DATE, %s)
ON CONFLICT (rate_date) DO NOTHING;
""", (gbp_to_inr,))

conn.commit()

In [39]:
df = pd.read_csv("books_raw.csv1")
df.head()

,title,price_gbp,availability,price_inr,in_stock,price_tier,product_id
0,A Light in the Attic,51.77,In stock,6370.014852,True,expensive,d682fd4bb45656063fc9eb088f20de3f
1,Tipping the Velvet,53.74,In stock,6612.412559,True,expensive,b771174bde49b2c24ef7ac178419435b
2,Soumission,50.10,In stock,6164.530502,True,expensive,0eeec5851efa6ebf8c0db9dfb6096e5e
3,Sharp Objects,47.82,In stock,5883.988994,True,expensive,86ff04a40b3e53b038b49a98207c0127
4,Sapiens: A Brief History of Humankind,54.23,In stock,6672.704374,True,expensive,c0e265b2cafdec9dfb4bc8c200c94d04

In [40]:
df["price_gbp"] = (
    df["price_gbp"]
    .astype(str)
    .str.replace("Â", "", regex=False)
    .str.replace("£", "", regex=False)
    .astype(float)
)
df

,title,price_gbp,availability,price_inr,in_stock,price_tier,product_id
0,A Light in the Attic,51.77,In stock,6370.014852,True,expensive,d682fd4bb45656063fc9eb088f20de3f
1,Tipping the Velvet,53.74,In stock,6612.412559,True,expensive,b771174bde49b2c24ef7ac178419435b
2,Soumission,50.10,In stock,6164.530502,True,expensive,0eeec5851efa6ebf8c0db9dfb6096e5e
3,Sharp Objects,47.82,In stock,5883.988994,True,expensive,86ff04a40b3e53b038b49a98207c0127
4,Sapiens: A Brief History of Humankind,54.23,In stock,6672.704374,True,expensive,c0e265b2cafdec9dfb4bc8c200c94d04
5,The Requiem Red,22.65,In stock,2786.958401,True,expensive,92684102e1573edd50e5e8b1c8cbd79f
6,The Dirty Little Secrets of Getting Your Dream...,33.34,In stock,4102.304330,True,expensive,c6c1ee76284bf714bc84f4c8c3cb4cb1
7,The Coming Woman: A Novel Based on the Life of...,17.93,In stock,2206.188262,True,expensive,28e839563e49bfeac720f65881b7eb20
8,The Boys in the Boat: Nine Americans and Their...,22.60,In stock,2780.806175,True,expensive,624397f941696d73072fdef59fe19b9e
9,The Black Maria,52.15,In stock,6416.771770,True,expensive,5720f7ba9b00df2a17e6f185ab3279e0
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,In stock,1721.392849,True,expensive,3c4eafd570c51d120b2a2881aad8db21
11,Shakespeare's Sonnets,20.66,In stock,2542.099804,True,expensive,2698ad152e638ab6102883d2e226a6df
12,Set Me Free,17.46,In stock,2148.357337,True,expensive,6d5ecb9ae143a4558abace775b9d92d1
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,In stock,6433.998003,True,expensive,5984eaa40046308a1c047a5e09bd44d6
14,Rip it Up and Start Again,35.02,In stock,4309.019125,True,expensive,2c14930331a3ebcbeb8d260a2316937e
15,Our Band Could Be Your Life: Scenes from the A...,57.25,In stock,7044.298827,True,expensive,cdfef026cc4f29254524d1dfa88dbcef
16,Olio,23.88,In stock,2938.303161,True,expensive,4ff1a6b98db96b039003b1ba97638338
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,In stock,4625.243544,True,expensive,9a3aa4a3c732788466eaf66b8f94b107
18,Libertarianism for Beginners,51.33,In stock,6315.875263,True,expensive,6dd1c169a1899748a500e397826d3de0
19,It's Only the Himalayas,45.17,In stock,5557.921014,True,expensive,6698d5e85cfc1b23c8c27331464b2fe0

In [41]:
for _, row in df.iterrows():
    cursor.execute("""
    INSERT INTO products (
        product_id, title,
        price_gbp, price_inr,
        in_stock, price_tier
    )
    VALUES (%s, %s, %s, %s, %s, %s)
    ON CONFLICT (product_id) DO UPDATE
    SET
        price_gbp = EXCLUDED.price_gbp,
        price_inr = EXCLUDED.price_inr,
        in_stock = EXCLUDED.in_stock,
        price_tier = EXCLUDED.price_tier;
    """, (
        row["product_id"],
        row["title"],
        row["price_gbp"],
        row["price_inr"],
        row["in_stock"],
        row["price_tier"]
    ))

In [42]:
conn.commit()

In [43]:
cursor.execute("SELECT * FROM products LIMIT 5;")
cursor.fetchall()

[('d682fd4bb45656063fc9eb088f20de3f',
  'A Light in the Attic',
  Decimal('51.77'),
  Decimal('6370.01485217'),
  True,
  'expensive'),
 ('b771174bde49b2c24ef7ac178419435b',
  'Tipping the Velvet',
  Decimal('53.74'),
  Decimal('6612.412558540001'),
  True,
  'expensive'),
 ('0eeec5851efa6ebf8c0db9dfb6096e5e',
  'Soumission',
  Decimal('50.1'),
  Decimal('6164.5305021'),
  True,
  'expensive'),
 ('86ff04a40b3e53b038b49a98207c0127',
  'Sharp Objects',
  Decimal('47.82'),
  Decimal('5883.98899422'),
  True,
  'expensive'),
 ('c0e265b2cafdec9dfb4bc8c200c94d04',
  'Sapiens: A Brief History of Humankind',
  Decimal('54.23'),
  Decimal('6672.70437383'),
  True,
  'expensive')]